project:
  type: website
  output-dir: _site
  preview:
    port: 4300
  render:
     - "*.qmd"
     - "!bib/"
#  resources:
#    - "bib"
#    - "img"

website:
  title: "Presentations"
  image: "img/CASA_Logo_no_text.png"
  repo-url: https://github.com/jreades/presentations/
  repo-actions: [issue]
  favicon: "/img/favicon.ico"
  page-navigation: true
  reader-mode: true
  page-footer: 
    left: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 2022, Jon Reades"
    center: "![](/img/favicon-16x16.png){.height:10px} Foundations of Spatial Data Science"
    right: 
      - icon: github
        href: https://github.com/jreades/fsds

bibliography: bib/Reades.bib
csl: bib/chicago-author-date.csl

highlight-style: pygments
format:
  html:
    theme: 
      - minty
      - css/web.scss
      - css/web.css
    code-copy: true
    code-link: true
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true
