---
bibliography: Sheffield.bib
csl: harvard-cite-them-right.csl
title: "Building Foundations: Pythonic (Geo)Data Science from the Ground Up"
author: Jon Reades, Centre for Advanced Spatial Analysis (UCL)
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    #documentclass: report
    mainfont: "Spectral" # https://fonts.google.com/specimen/Spectral
    sansfont: "Roboto Flex"   # https://fonts.google.com/specimen/Roboto?category=Sans+Serif
    monofont: "Roboto Mono" # https://fonts.google.com/specimen/Inconsolata
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=25mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
    highlight-style: github
---

Embedding reproducibility in the development, teaching, and assessment of undergraduate and postgraduate modules can benefit both students and staff: students learn how to apply essential programming tools in an appropriate context — developing relevant employability skills — while staff spend less time on installation and maintenance tasks. In this short presentation I will briefly review the philosophy underpinning our *Foundations of Data Science* module and explain how and why this module has evolved over the past decade towards the kind of reproducibility framework outlined in @dogucu:2022 and the practices and tools set out in @Ostblom:2022. Along the way, we have taken in — sometimes almost despite ourselves — an ever-larger range of the tools and practices that programmers and data scientists employ on real-world projects. 

Building on earlier work with Jupyter and Git/GitHub [@reades:2020; @reades:2021], I will show how we now *also* make use of [Docker](https://www.docker.com) and [Quarto](https://quarto.org) as part of a 'flipped' module that enables us to spend less time on administrative tasks and debugging installation issues, and more time focussing on critical module maintenance and in-person teaching. By incorporating replicability and reproducibility into our assessment requirements and practices — and repeatedly stressing their relevance to dissertation management and employment — we seek to 'bed in' these concepts as part of student thinking and workflows as well. Ultimately, we find that what we learn in preparing and managing this *Foundations* module has fed back into our own research practices, encouraging the broader adoption of open, reproducible workflows (e.g. Docker, Markdown, and Pandoc).

As universities try to resume 'business as usual' after years of pandemic disruption, lecturers and course instructors need ways to address the amount of work involved in producing and maintaining 'computational social science' [@lazer:2009] teaching materials. And as we argued in @reades:2021, we also need *better* ways to be recognised by peers and institutions for the efforts underpinning our contributions to the wider community [e.g. @arribas:2019; @maclachlan:2022]. Reproducible workflows and open source teaching materials provide one way of working towards this goal, enabling others to learn from, and build on, our learning while also (slowly) reducing the amount of labour that this process entails. I will wrap up with a brief overview of what we're working on *now*; this includes incorporating Continuous Integration and GitHub Issues/Pull Requests into the maintenance process, and enabling the automated, incremental update of slides and videos.

### References
